# Dockerfile.frontend

# Use Node.js 18 image
FROM node:18

WORKDIR /app

# Copy files to container
COPY . .

# Install dependencies and build the project
RUN npm install && npm run build

# Expose port
EXPOSE 5000

# Run the application
CMD ["npm", "run", "dev", "--host"]
